name: test

on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        odoo-version:
          - 13.0
          - 14.0
    steps:
      # Prepare environment
      - uses: actions/checkout@v2.3.3
      - name: Install python
        uses: actions/setup-python@v2
      - name: Patch $PATH
        run: echo "::set-env name=PATH::$HOME/.local/bin:$PATH"
      - run: pip install pipx
      - run: pipx install poetry
      - uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cache
            ~/.local
          # HACK https://github.com/actions/cache/issues/2#issuecomment-673493515
          # If you need to "clear" cache, just update the `CACHE_DATE` secret,
          # putting current date (and time, if needed)
          key: >-
            cache ${{ secrets.CACHE_DATE }} ${{ env.PY }} ${{ runner.os }} $(python -VV
            | sha256sum) $(pipx --version | sha256sum) $(poetry --version | sha256sum)
            ${{ hashFiles('pyproject.toml') }} ${{ hashFiles('poetry.lock') }}
      - run: poetry install

      # Let tests issue git commits
      - run: git config --global user.name CI
      - run: git config --global user.email CI@GITHUB

      # Run all tests
      - run: poetry run pytest --color yes
        env:
          SELECTED_ODOO_VERSIONS: ${{ matrix.odoo-version }}
